In [1]:
from scipy import *
from numpy.linalg import svd
from numpy import *
from time import *
res=0
for i in range(1):
    if i%50==0: print(i,)
    while True:
        A=floor(2*rand(7,3))
        if dot(A[0],A[1])%2==1 and dot(A[1],A[2])%2==1 and dot(A[0],A[3])%2==1:
            break
    print(A)
    u,S,v=svd(A,full_matrices=True)
    Z=zeros((7,3))
    Z[0,0],Z[1,1],Z[2,2]=S
    print(Z)
    print(dot(u,dot(Z,v)-A))
    a=time()
    for i in range(100000):
        B=floor(2*rand(7,3))
        if sum(abs(dot(transpose(A),B)%2-eye(3)))==0:
            #print(abs(dot(transpose(A),B)%2))
            print(B,i)
            break
    
    res+=time()-a
print(res/1)

0
[[ 0.  1.  0.]
 [ 1.  1.  0.]
 [ 0.  1.  1.]
 [ 1.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]
[[ 2.48635141  0.          0.        ]
 [ 0.          1.55126421  0.        ]
 [ 0.          0.          1.18812289]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.28751591  1.04472908 -1.30421196]
 [ 1.69317807  1.76874068  0.85757092]
 [ 0.22310353  0.94015011  1.04054098]
 [-0.27294597  0.69887987 -0.26696859]
 [ 1.39361579  1.73649152  1.37143537]
 [ 0.          0.          0.        ]
 [ 0.78213729  0.54532462  0.40609492]]
[[ 1.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  1.  0.]
 [ 0.  0.  1.]] 828
0.013879537582397461


In [28]:
print(res/500)

0.06529388809204102
